### ISSUE TITLE
Bug raised when inferring align vanilla model on ESConv

### ISSUE THREAD

**Issue by neilwen987** [wangjs9/Aligned-dPM#1]
When I am using the command". RUN/align_vanilla.sh {gpu_id} {model_path}" to align the vanilla model on ESConv. Bug occurs when inferring the model
 ![image](https://github.com/user-attachments/assets/51b0737c-fefa-492f-811a-540708dc79bf)
![image](https://github.com/user-attachments/assets/bd2914e3-2461-4d7b-aa9e-59c9bd4e65b3)
Any solution?

**Comment by wangjs9** [comment]
I ran the code and did not encounter this problem. I recommend searching for the error online to see if there are any solutions. Good luck!
